apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: muhammadabdulraheem/user-api-go:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 50Mi
              cpu: 100m