apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: users-api-ingress
  namespace: main-namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{.Values.ingressScheme}}
    alb.ingress.kubernetes.io/group.name: {{.Values.ingressGroup}}
  labels:
    app: users-api
spec:
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - path: /*
            backend:
              serviceName: users-api
              servicePort: 443