apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: main-namespace
  labels:
    app.kubernetes.io/name: users-api
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service  }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
