apiVersion: v1
kind: Service
metadata:
  name: mongodb-metrics
  labels:
    app: mongo
spec:
  type: ClusterIP
  ports:
    - port: 9216
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector:
    app: mongo
